- name: Apache installation to Amz Linux 2 servers
  hosts: webservers
  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: latest
  
  - name: start Apache service
    shell: "service httpd start"

- name: Apache installation to Amz Ubuntu servers
  hosts: ubuntuserver
  tasks:
  - name: make a system update
    ansible.builtin.shell: "apt update -y"
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: apache2
      state: present
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: apache2
      state: started