- name: Copy testfile1 to my webservers
  hosts: webservers
  tasks:
  - name: Copy testfile1
    copy:
      src: /home/ec2-user/testfile1
      dest: /home/ec2-user/testfile1

- name: Copy testfile1 to my Ubuntu server
  hosts: ubuntuservers
  tasks:
  - name: Copy testfile1
    copy:
      src: /home/ec2-user/testfile1
      dest: /home/ubuntu/testfile1